# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

baseline_cont <- function(x, y) {
    .Call(`_eegUtils_baseline_cont`, x, y)
}

baseline_epo <- function(x, x_m) {
    .Call(`_eegUtils_baseline_epo`, x, x_m)
}

get_list <- function(x, mors, n_kern, output) {
    .Call(`_eegUtils_get_list`, x, mors, n_kern, output)
}

get_listal <- function(x, mors, n_kern, output) {
    .Call(`_eegUtils_get_listal`, x, mors, n_kern, output)
}

get_list2 <- function(x, mors, n_kern, output) {
    .Call(`_eegUtils_get_list2`, x, mors, n_kern, output)
}

